language: java
install: skip

os: linux
dist: trusty
jdk: oraclejdk11

env:
  - TERM=dumb

services:
  - mysql

script:
  - cd server
  - cp config.example.json config.json
  - chmod +x gradlew
  - ./gradlew test